CREATE TABLE tag
(
    id          bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    change_date timestamp without time zone,
    create_time timestamp without time zone,
    name        character varying(50) COLLATE pg_catalog."default",
    PRIMARY KEY (id)
);

CREATE TABLE public.folder
(
    id          bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    change_date timestamp without time zone,
    create_time timestamp without time zone,
    name        character varying(255) COLLATE pg_catalog."default",
    PRIMARY KEY (id)
);

CREATE TABLE request
(
    id          bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    change_date timestamp without time zone,
    create_time timestamp without time zone,
    length      integer,
    text        character varying(2048),
    folder_id   bigint,
    PRIMARY KEY (id),
    CONSTRAINT folder_fk FOREIGN KEY (folder_id) REFERENCES folder (id)
);

CREATE TABLE tag_to_request
(
    tag_id     bigint NOT NULL,
    request_id bigint NOT NULL,
    PRIMARY KEY (tag_id, request_id),
    CONSTRAINT request_fk FOREIGN KEY (request_id) REFERENCES tag (id),
    CONSTRAINT tag_fk FOREIGN KEY (tag_id) REFERENCES request (id)
);

CREATE TABLE public.request_to_folder
(
    request_id bigint NOT NULL,
    folder_id  bigint NOT NULL,
    PRIMARY KEY (request_id, folder_id),
    CONSTRAINT folder_uk UNIQUE (folder_id),
    CONSTRAINT request_fk FOREIGN KEY (request_id) REFERENCES folder (id),
    CONSTRAINT folder_fk FOREIGN KEY (folder_id) REFERENCES request (id)
);